// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"github.com/tqhuy-dev/gore/templates/applications/internal/services"
)

// Injectors from wire.go:

func NewApiApp() (BaseApiApp, func(), error) {
	sampleService := services.NewSampleService()
	baseApiApp := NewBaseApiApp(sampleService)
	return baseApiApp, func() {
	}, nil
}
