// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: health.proto

package pb

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReadinessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadinessRequest) Reset() {
	*x = ReadinessRequest{}
	mi := &file_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadinessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadinessRequest) ProtoMessage() {}

func (x *ReadinessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadinessRequest.ProtoReflect.Descriptor instead.
func (*ReadinessRequest) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{0}
}

type ReadinessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadinessResponse) Reset() {
	*x = ReadinessResponse{}
	mi := &file_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadinessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadinessResponse) ProtoMessage() {}

func (x *ReadinessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadinessResponse.ProtoReflect.Descriptor instead.
func (*ReadinessResponse) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{1}
}

func (x *ReadinessResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type SamplingReturn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          int32                  `protobuf:"varint,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SamplingReturn) Reset() {
	*x = SamplingReturn{}
	mi := &file_health_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SamplingReturn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SamplingReturn) ProtoMessage() {}

func (x *SamplingReturn) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SamplingReturn.ProtoReflect.Descriptor instead.
func (*SamplingReturn) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{2}
}

func (x *SamplingReturn) GetData() int32 {
	if x != nil {
		return x.Data
	}
	return 0
}

type SampRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          int32                  `protobuf:"varint,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SampRequest) Reset() {
	*x = SampRequest{}
	mi := &file_health_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SampRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SampRequest) ProtoMessage() {}

func (x *SampRequest) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SampRequest.ProtoReflect.Descriptor instead.
func (*SampRequest) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{3}
}

func (x *SampRequest) GetData() int32 {
	if x != nil {
		return x.Data
	}
	return 0
}

var File_health_proto protoreflect.FileDescriptor

const file_health_proto_rawDesc = "" +
	"\n" +
	"\fhealth.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"\x12\n" +
	"\x10ReadinessRequest\"-\n" +
	"\x11ReadinessResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"$\n" +
	"\x0eSamplingReturn\x12\x12\n" +
	"\x04data\x18\x01 \x01(\x05R\x04data\"*\n" +
	"\vSampRequest\x12\x1b\n" +
	"\x04data\x18\x01 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\x04data2\xb8\x01\n" +
	"\x12HealthCheckService\x12T\n" +
	"\x0eReadinessCheck\x12\x14.pb.ReadinessRequest\x1a\x15.pb.ReadinessResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/readiness\x12L\n" +
	"\x0fSamplingRequest\x12\x0f.pb.SampRequest\x1a\x12.pb.SamplingReturn\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/samplingB\x1eZ\x1cgithub.com/tqhuy-dev/gore/pbb\x06proto3"

var (
	file_health_proto_rawDescOnce sync.Once
	file_health_proto_rawDescData []byte
)

func file_health_proto_rawDescGZIP() []byte {
	file_health_proto_rawDescOnce.Do(func() {
		file_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_health_proto_rawDesc), len(file_health_proto_rawDesc)))
	})
	return file_health_proto_rawDescData
}

var file_health_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_health_proto_goTypes = []any{
	(*ReadinessRequest)(nil),  // 0: pb.ReadinessRequest
	(*ReadinessResponse)(nil), // 1: pb.ReadinessResponse
	(*SamplingReturn)(nil),    // 2: pb.SamplingReturn
	(*SampRequest)(nil),       // 3: pb.SampRequest
}
var file_health_proto_depIdxs = []int32{
	0, // 0: pb.HealthCheckService.ReadinessCheck:input_type -> pb.ReadinessRequest
	3, // 1: pb.HealthCheckService.SamplingRequest:input_type -> pb.SampRequest
	1, // 2: pb.HealthCheckService.ReadinessCheck:output_type -> pb.ReadinessResponse
	2, // 3: pb.HealthCheckService.SamplingRequest:output_type -> pb.SamplingReturn
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_health_proto_init() }
func file_health_proto_init() {
	if File_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_health_proto_rawDesc), len(file_health_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_health_proto_goTypes,
		DependencyIndexes: file_health_proto_depIdxs,
		MessageInfos:      file_health_proto_msgTypes,
	}.Build()
	File_health_proto = out.File
	file_health_proto_goTypes = nil
	file_health_proto_depIdxs = nil
}
