// Copyright (c) 2018 Uber Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: model.proto

package pb

import (
	_ "github.com/temporalio/gogo-protobuf/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValueType int32

const (
	ValueType_STRING  ValueType = 0
	ValueType_BOOL    ValueType = 1
	ValueType_INT64   ValueType = 2
	ValueType_FLOAT64 ValueType = 3
	ValueType_BINARY  ValueType = 4
)

// Enum value maps for ValueType.
var (
	ValueType_name = map[int32]string{
		0: "STRING",
		1: "BOOL",
		2: "INT64",
		3: "FLOAT64",
		4: "BINARY",
	}
	ValueType_value = map[string]int32{
		"STRING":  0,
		"BOOL":    1,
		"INT64":   2,
		"FLOAT64": 3,
		"BINARY":  4,
	}
)

func (x ValueType) Enum() *ValueType {
	p := new(ValueType)
	*p = x
	return p
}

func (x ValueType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValueType) Descriptor() protoreflect.EnumDescriptor {
	return file_model_proto_enumTypes[0].Descriptor()
}

func (ValueType) Type() protoreflect.EnumType {
	return &file_model_proto_enumTypes[0]
}

func (x ValueType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValueType.Descriptor instead.
func (ValueType) EnumDescriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{0}
}

type SpanRefType int32

const (
	SpanRefType_CHILD_OF     SpanRefType = 0
	SpanRefType_FOLLOWS_FROM SpanRefType = 1
)

// Enum value maps for SpanRefType.
var (
	SpanRefType_name = map[int32]string{
		0: "CHILD_OF",
		1: "FOLLOWS_FROM",
	}
	SpanRefType_value = map[string]int32{
		"CHILD_OF":     0,
		"FOLLOWS_FROM": 1,
	}
)

func (x SpanRefType) Enum() *SpanRefType {
	p := new(SpanRefType)
	*p = x
	return p
}

func (x SpanRefType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SpanRefType) Descriptor() protoreflect.EnumDescriptor {
	return file_model_proto_enumTypes[1].Descriptor()
}

func (SpanRefType) Type() protoreflect.EnumType {
	return &file_model_proto_enumTypes[1]
}

func (x SpanRefType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SpanRefType.Descriptor instead.
func (SpanRefType) EnumDescriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{1}
}

type KeyValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key   string    `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	VType ValueType `protobuf:"varint,2,opt,name=v_type,json=vType,proto3,enum=jaeger.api_v2.ValueType" json:"v_type,omitempty"`
	VStr  string    `protobuf:"bytes,3,opt,name=v_str,json=vStr,proto3" json:"v_str,omitempty"`
	VBool         bool                   `protobuf:"varint,4,opt,name=v_bool,json=vBool,proto3" json:"v_bool,omitempty"`
	VInt64        int64                  `protobuf:"varint,5,opt,name=v_int64,json=vInt64,proto3" json:"v_int64,omitempty"`
	VFloat64      float64                `protobuf:"fixed64,6,opt,name=v_float64,json=vFloat64,proto3" json:"v_float64,omitempty"`
	VBinary       []byte                 `protobuf:"bytes,7,opt,name=v_binary,json=vBinary,proto3" json:"v_binary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{0}
}

func (x *KeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValue) GetVType() ValueType {
	if x != nil {
		return x.VType
	}
	return ValueType_STRING
}

func (x *KeyValue) GetVStr() string {
	if x != nil {
		return x.VStr
	}
	return ""
}

func (x *KeyValue) GetVBool() bool {
	if x != nil {
		return x.VBool
	}
	return false
}

func (x *KeyValue) GetVInt64() int64 {
	if x != nil {
		return x.VInt64
	}
	return 0
}

func (x *KeyValue) GetVFloat64() float64 {
	if x != nil {
		return x.VFloat64
	}
	return 0
}

func (x *KeyValue) GetVBinary() []byte {
	if x != nil {
		return x.VBinary
	}
	return nil
}

type Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Fields        []*KeyValue            `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{1}
}

func (x *Log) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Log) GetFields() []*KeyValue {
	if x != nil {
		return x.Fields
	}
	return nil
}

type SpanRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       []byte                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId        []byte      `protobuf:"bytes,2,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	RefType       SpanRefType `protobuf:"varint,3,opt,name=ref_type,json=refType,proto3,enum=jaeger.api_v2.SpanRefType" json:"ref_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpanRef) Reset() {
	*x = SpanRef{}
	mi := &file_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpanRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpanRef) ProtoMessage() {}

func (x *SpanRef) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpanRef.ProtoReflect.Descriptor instead.
func (*SpanRef) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{2}
}

func (x *SpanRef) GetTraceId() []byte {
	if x != nil {
		return x.TraceId
	}
	return nil
}

func (x *SpanRef) GetSpanId() []byte {
	if x != nil {
		return x.SpanId
	}
	return nil
}

func (x *SpanRef) GetRefType() SpanRefType {
	if x != nil {
		return x.RefType
	}
	return SpanRefType_CHILD_OF
}

type Process struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string      `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Tags          []*KeyValue `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Process) Reset() {
	*x = Process{}
	mi := &file_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Process) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Process) ProtoMessage() {}

func (x *Process) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Process.ProtoReflect.Descriptor instead.
func (*Process) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{3}
}

func (x *Process) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Process) GetTags() []*KeyValue {
	if x != nil {
		return x.Tags
	}
	return nil
}

type Span struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       []byte                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId        []byte                 `protobuf:"bytes,2,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	OperationName string               `protobuf:"bytes,3,opt,name=operation_name,json=operationName,proto3" json:"operation_name,omitempty"`
	References    []*SpanRef           `protobuf:"bytes,4,rep,name=references,proto3" json:"references,omitempty"`
	Flags         uint32               `protobuf:"varint,5,opt,name=flags,proto3" json:"flags,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Duration      *durationpb.Duration `protobuf:"bytes,7,opt,name=duration,proto3" json:"duration,omitempty"`
	Tags          []*KeyValue          `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	Logs          []*Log               `protobuf:"bytes,9,rep,name=logs,proto3" json:"logs,omitempty"`
	Process       *Process             `protobuf:"bytes,10,opt,name=process,proto3" json:"process,omitempty"`
	ProcessId     string               `protobuf:"bytes,11,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	Warnings      []string               `protobuf:"bytes,12,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Span) Reset() {
	*x = Span{}
	mi := &file_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Span) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Span) ProtoMessage() {}

func (x *Span) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Span.ProtoReflect.Descriptor instead.
func (*Span) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{4}
}

func (x *Span) GetTraceId() []byte {
	if x != nil {
		return x.TraceId
	}
	return nil
}

func (x *Span) GetSpanId() []byte {
	if x != nil {
		return x.SpanId
	}
	return nil
}

func (x *Span) GetOperationName() string {
	if x != nil {
		return x.OperationName
	}
	return ""
}

func (x *Span) GetReferences() []*SpanRef {
	if x != nil {
		return x.References
	}
	return nil
}

func (x *Span) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *Span) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Span) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *Span) GetTags() []*KeyValue {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Span) GetLogs() []*Log {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *Span) GetProcess() *Process {
	if x != nil {
		return x.Process
	}
	return nil
}

func (x *Span) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *Span) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

type Trace struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Spans         []*Span                 `protobuf:"bytes,1,rep,name=spans,proto3" json:"spans,omitempty"`
	ProcessMap    []*Trace_ProcessMapping `protobuf:"bytes,2,rep,name=process_map,json=processMap,proto3" json:"process_map,omitempty"`
	Warnings      []string                `protobuf:"bytes,3,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trace) Reset() {
	*x = Trace{}
	mi := &file_model_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trace) ProtoMessage() {}

func (x *Trace) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trace.ProtoReflect.Descriptor instead.
func (*Trace) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{5}
}

func (x *Trace) GetSpans() []*Span {
	if x != nil {
		return x.Spans
	}
	return nil
}

func (x *Trace) GetProcessMap() []*Trace_ProcessMapping {
	if x != nil {
		return x.ProcessMap
	}
	return nil
}

func (x *Trace) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

// Note that both Span and Batch may contain a Process.
// This is different from the Thrift model which was only used
// for transport, because Proto model is also used by the backend
// as the domain model, where once a batch is received it is split
// into individual spans which are all processed independently,
// and therefore they all need a Process. As far as on-the-wire
// semantics, both Batch and Spans in the same message may contain
// their own instances of Process, with span.Process taking priority
// over batch.Process.
type Batch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spans         []*Span                `protobuf:"bytes,1,rep,name=spans,proto3" json:"spans,omitempty"`
	Process       *Process               `protobuf:"bytes,2,opt,name=process,proto3" json:"process,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Batch) Reset() {
	*x = Batch{}
	mi := &file_model_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Batch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Batch) ProtoMessage() {}

func (x *Batch) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Batch.ProtoReflect.Descriptor instead.
func (*Batch) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{6}
}

func (x *Batch) GetSpans() []*Span {
	if x != nil {
		return x.Spans
	}
	return nil
}

func (x *Batch) GetProcess() *Process {
	if x != nil {
		return x.Process
	}
	return nil
}

type DependencyLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Child         string                 `protobuf:"bytes,2,opt,name=child,proto3" json:"child,omitempty"`
	CallCount     uint64                 `protobuf:"varint,3,opt,name=call_count,json=callCount,proto3" json:"call_count,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DependencyLink) Reset() {
	*x = DependencyLink{}
	mi := &file_model_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DependencyLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependencyLink) ProtoMessage() {}

func (x *DependencyLink) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependencyLink.ProtoReflect.Descriptor instead.
func (*DependencyLink) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{7}
}

func (x *DependencyLink) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *DependencyLink) GetChild() string {
	if x != nil {
		return x.Child
	}
	return ""
}

func (x *DependencyLink) GetCallCount() uint64 {
	if x != nil {
		return x.CallCount
	}
	return 0
}

func (x *DependencyLink) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type Trace_ProcessMapping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessId     string   `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	Process       *Process `protobuf:"bytes,2,opt,name=process,proto3" json:"process,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trace_ProcessMapping) Reset() {
	*x = Trace_ProcessMapping{}
	mi := &file_model_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trace_ProcessMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trace_ProcessMapping) ProtoMessage() {}

func (x *Trace_ProcessMapping) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trace_ProcessMapping.ProtoReflect.Descriptor instead.
func (*Trace_ProcessMapping) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{5, 0}
}

func (x *Trace_ProcessMapping) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *Trace_ProcessMapping) GetProcess() *Process {
	if x != nil {
		return x.Process
	}
	return nil
}

var File_model_proto protoreflect.FileDescriptor

const file_model_proto_rawDesc = "" +
	"\n" +
	"\vmodel.proto\x12\rjaeger.api_v2\x1a\x14gogoproto/gogo.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\xd4\x01\n" +
	"\bKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x06v_type\x18\x02 \x01(\x0e2\x18.jaeger.api_v2.ValueTypeR\x05vType\x12\x13\n" +
	"\x05v_str\x18\x03 \x01(\tR\x04vStr\x12\x15\n" +
	"\x06v_bool\x18\x04 \x01(\bR\x05vBool\x12\x17\n" +
	"\av_int64\x18\x05 \x01(\x03R\x06vInt64\x12\x1b\n" +
	"\tv_float64\x18\x06 \x01(\x01R\bvFloat64\x12\x19\n" +
	"\bv_binary\x18\a \x01(\fR\avBinary:\b\xe8\xa0\x1f\x01\xe8\xa1\x1f\x01\"\x80\x01\n" +
	"\x03Log\x12B\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB\b\xc8\xde\x1f\x00\x90\xdf\x1f\x01R\ttimestamp\x125\n" +
	"\x06fields\x18\x02 \x03(\v2\x17.jaeger.api_v2.KeyValueB\x04\xc8\xde\x1f\x00R\x06fields\"\xaa\x01\n" +
	"\aSpanRef\x125\n" +
	"\btrace_id\x18\x01 \x01(\fB\x1a\xc8\xde\x1f\x00\xda\xde\x1f\aTraceID\xe2\xde\x1f\aTraceIDR\atraceId\x121\n" +
	"\aspan_id\x18\x02 \x01(\fB\x18\xc8\xde\x1f\x00\xda\xde\x1f\x06SpanID\xe2\xde\x1f\x06SpanIDR\x06spanId\x125\n" +
	"\bref_type\x18\x03 \x01(\x0e2\x1a.jaeger.api_v2.SpanRefTypeR\arefType\"_\n" +
	"\aProcess\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x121\n" +
	"\x04tags\x18\x02 \x03(\v2\x17.jaeger.api_v2.KeyValueB\x04\xc8\xde\x1f\x00R\x04tags\"\xdd\x04\n" +
	"\x04Span\x125\n" +
	"\btrace_id\x18\x01 \x01(\fB\x1a\xc8\xde\x1f\x00\xda\xde\x1f\aTraceID\xe2\xde\x1f\aTraceIDR\atraceId\x121\n" +
	"\aspan_id\x18\x02 \x01(\fB\x18\xc8\xde\x1f\x00\xda\xde\x1f\x06SpanID\xe2\xde\x1f\x06SpanIDR\x06spanId\x12%\n" +
	"\x0eoperation_name\x18\x03 \x01(\tR\roperationName\x12<\n" +
	"\n" +
	"references\x18\x04 \x03(\v2\x16.jaeger.api_v2.SpanRefB\x04\xc8\xde\x1f\x00R\n" +
	"references\x12#\n" +
	"\x05flags\x18\x05 \x01(\rB\r\xc8\xde\x1f\x00\xda\xde\x1f\x05FlagsR\x05flags\x12C\n" +
	"\n" +
	"start_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\b\xc8\xde\x1f\x00\x90\xdf\x1f\x01R\tstartTime\x12?\n" +
	"\bduration\x18\a \x01(\v2\x19.google.protobuf.DurationB\b\xc8\xde\x1f\x00\x98\xdf\x1f\x01R\bduration\x121\n" +
	"\x04tags\x18\b \x03(\v2\x17.jaeger.api_v2.KeyValueB\x04\xc8\xde\x1f\x00R\x04tags\x12,\n" +
	"\x04logs\x18\t \x03(\v2\x12.jaeger.api_v2.LogB\x04\xc8\xde\x1f\x00R\x04logs\x120\n" +
	"\aprocess\x18\n" +
	" \x01(\v2\x16.jaeger.api_v2.ProcessR\aprocess\x12,\n" +
	"\n" +
	"process_id\x18\v \x01(\tB\r\xe2\xde\x1f\tProcessIDR\tprocessId\x12\x1a\n" +
	"\bwarnings\x18\f \x03(\tR\bwarnings\"\x92\x02\n" +
	"\x05Trace\x12)\n" +
	"\x05spans\x18\x01 \x03(\v2\x13.jaeger.api_v2.SpanR\x05spans\x12J\n" +
	"\vprocess_map\x18\x02 \x03(\v2#.jaeger.api_v2.Trace.ProcessMappingB\x04\xc8\xde\x1f\x00R\n" +
	"processMap\x12\x1a\n" +
	"\bwarnings\x18\x03 \x03(\tR\bwarnings\x1av\n" +
	"\x0eProcessMapping\x12,\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tB\r\xe2\xde\x1f\tProcessIDR\tprocessId\x126\n" +
	"\aprocess\x18\x02 \x01(\v2\x16.jaeger.api_v2.ProcessB\x04\xc8\xde\x1f\x00R\aprocess\"j\n" +
	"\x05Batch\x12)\n" +
	"\x05spans\x18\x01 \x03(\v2\x13.jaeger.api_v2.SpanR\x05spans\x126\n" +
	"\aprocess\x18\x02 \x01(\v2\x16.jaeger.api_v2.ProcessB\x04\xc8\xde\x1f\x01R\aprocess\"u\n" +
	"\x0eDependencyLink\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12\x14\n" +
	"\x05child\x18\x02 \x01(\tR\x05child\x12\x1d\n" +
	"\n" +
	"call_count\x18\x03 \x01(\x04R\tcallCount\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source*E\n" +
	"\tValueType\x12\n" +
	"\n" +
	"\x06STRING\x10\x00\x12\b\n" +
	"\x04BOOL\x10\x01\x12\t\n" +
	"\x05INT64\x10\x02\x12\v\n" +
	"\aFLOAT64\x10\x03\x12\n" +
	"\n" +
	"\x06BINARY\x10\x04*-\n" +
	"\vSpanRefType\x12\f\n" +
	"\bCHILD_OF\x10\x00\x12\x10\n" +
	"\fFOLLOWS_FROM\x10\x01BC\xc8\xe2\x1e\x01\xd0\xe2\x1e\x01\xe0\xe2\x1e\x01\n" +
	"\x17io.jaegertracing.api_v2Z\x1cgithub.com/tqhuy-dev/gore/pbb\x06proto3"

var (
	file_model_proto_rawDescOnce sync.Once
	file_model_proto_rawDescData []byte
)

func file_model_proto_rawDescGZIP() []byte {
	file_model_proto_rawDescOnce.Do(func() {
		file_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_proto_rawDesc), len(file_model_proto_rawDesc)))
	})
	return file_model_proto_rawDescData
}

var file_model_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_model_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_model_proto_goTypes = []any{
	(ValueType)(0),                // 0: jaeger.api_v2.ValueType
	(SpanRefType)(0),              // 1: jaeger.api_v2.SpanRefType
	(*KeyValue)(nil),              // 2: jaeger.api_v2.KeyValue
	(*Log)(nil),                   // 3: jaeger.api_v2.Log
	(*SpanRef)(nil),               // 4: jaeger.api_v2.SpanRef
	(*Process)(nil),               // 5: jaeger.api_v2.Process
	(*Span)(nil),                  // 6: jaeger.api_v2.Span
	(*Trace)(nil),                 // 7: jaeger.api_v2.Trace
	(*Batch)(nil),                 // 8: jaeger.api_v2.Batch
	(*DependencyLink)(nil),        // 9: jaeger.api_v2.DependencyLink
	(*Trace_ProcessMapping)(nil),  // 10: jaeger.api_v2.Trace.ProcessMapping
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 12: google.protobuf.Duration
}
var file_model_proto_depIdxs = []int32{
	0,  // 0: jaeger.api_v2.KeyValue.v_type:type_name -> jaeger.api_v2.ValueType
	11, // 1: jaeger.api_v2.Log.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 2: jaeger.api_v2.Log.fields:type_name -> jaeger.api_v2.KeyValue
	1,  // 3: jaeger.api_v2.SpanRef.ref_type:type_name -> jaeger.api_v2.SpanRefType
	2,  // 4: jaeger.api_v2.Process.tags:type_name -> jaeger.api_v2.KeyValue
	4,  // 5: jaeger.api_v2.Span.references:type_name -> jaeger.api_v2.SpanRef
	11, // 6: jaeger.api_v2.Span.start_time:type_name -> google.protobuf.Timestamp
	12, // 7: jaeger.api_v2.Span.duration:type_name -> google.protobuf.Duration
	2,  // 8: jaeger.api_v2.Span.tags:type_name -> jaeger.api_v2.KeyValue
	3,  // 9: jaeger.api_v2.Span.logs:type_name -> jaeger.api_v2.Log
	5,  // 10: jaeger.api_v2.Span.process:type_name -> jaeger.api_v2.Process
	6,  // 11: jaeger.api_v2.Trace.spans:type_name -> jaeger.api_v2.Span
	10, // 12: jaeger.api_v2.Trace.process_map:type_name -> jaeger.api_v2.Trace.ProcessMapping
	6,  // 13: jaeger.api_v2.Batch.spans:type_name -> jaeger.api_v2.Span
	5,  // 14: jaeger.api_v2.Batch.process:type_name -> jaeger.api_v2.Process
	5,  // 15: jaeger.api_v2.Trace.ProcessMapping.process:type_name -> jaeger.api_v2.Process
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_model_proto_init() }
func file_model_proto_init() {
	if File_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_proto_rawDesc), len(file_model_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_proto_goTypes,
		DependencyIndexes: file_model_proto_depIdxs,
		EnumInfos:         file_model_proto_enumTypes,
		MessageInfos:      file_model_proto_msgTypes,
	}.Build()
	File_model_proto = out.File
	file_model_proto_goTypes = nil
	file_model_proto_depIdxs = nil
}
