package cmd

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
	"github.com/tqhuy-dev/gore/templates/applications/cmd/api"
)

var RootCmd = &cobra.Command{
	Use:   "myapp",
	Short: "MyApp",
	Long:  `MyApp is generated by r-kit`,
}

func init() {
	RootCmd.AddCommand(
		&cobra.Command{
			Use:   "api",
			Short: "Run API server",
			Run: func(cmd *cobra.Command, args []string) {
				fmt.Println("Starting API server...")
				api.RunAPIServer()
			},
		})
}

// Execute là entry point của CLI
func Execute() {
	if err := RootCmd.Execute(); err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}
